### ISSUE TITLE
In the settings.yml of configs, the language defaultLocale has been changed to zh_ CN, but the default language used after the container restarts is still English

### ISSUE THREAD

**Issue by 1411v6** [Frooodle/Stirling-PDF#481] opened 2023-11-21 03:53 UTC
In the settings.yml of configs, the language defaultLocale has been changed to zh_ CN, but the default language used after the container restarts is still English

![1232131](https://github.com/Frooodle/Stirling-PDF/assets/45678155/1f9807c3-7ac8-48c1-8489-df3860fa2ff8)
![2222](https://github.com/Frooodle/Stirling-PDF/assets/45678155/68821e95-04da-4e08-be50-88dfc0b057a6)

**Comment by Frooodle** [comment] 2023-12-11 17:53
Did you try with a -

**Comment by Frooodle** [comment] 2023-12-16 20:41
closing due to no reply

**Closed by Frooodle** 2023-12-16 20:41 UTC

**Comment by gepcel** [comment] 2024-01-05 07:42
> Did you try with a -

Can you elaborate on this?
I have the same issue. I've stopped the container, modified the system.yaml, as following, and restarted the container, the startup page is still in English.

```
system:
  defaultLocale: 'zh_CN' # Set the default language (e.g. 'de-DE', 'fr-FR', etc)
```

**Comment by gepcel** [comment] 2024-01-05 08:07
Ok, now I can confirm that changing 'zh_CN' to 'zh-CN' works.
