### ISSUE TITLE
feature request - log failed login attempts

### ISSUE THREAD

**Issue by timmish** [Frooodle/Stirling-PDF#522] opened 2023-12-12 18:35 UTC
Hello team,
it would be very nice if StirlingPDF would log the case that someone tried logging in but wasn't successful.
I would love to setup fail2ban inside SWAG for Stirling-PDF.

Thanks you guys for your work.

**Comment by Frooodle** [comment] 2023-12-12 18:47
What would you want the log to show

just failed for IP : x.x.x.x ?

**Comment by timmish** [comment] 2023-12-12 18:53
A timestamp at the beginning of the line, followed by something like “failed login attempt from IP x.x.x.x” would be Perfect. 
And it should show the real IP and not the one of the remote proxy - some tools have an extra toggle or setting for that. 

Thanks for the quick reply!

**Comment by Frooodle** [comment] 2023-12-16 12:07
"And it should show the real IP and not the one of the remote proxy "
This one i am unsure about sorry however i can get the general remote address

**Comment by timmish** [comment] 2023-12-16 12:33
Yeah nice let’s start with that and maybe that already solves it 100% 😄
Have a great weekend!

**Comment by Frooodle** [comment] 2023-12-16 20:35
released in latest 0.17.0!

**Closed by Frooodle** 2023-12-16 20:35 UTC
Labels: Prioritised enhancement, Done for next release

**Comment by Frooodle** [comment] 2023-12-17 19:47
@timmish please let me know if it works as intended!

**Comment by timmish** [comment] 2023-12-17 21:10
Just tried it and it’s perfect! The IP was the correct one and the extra log folder is an awesome addition, I was working with syslog via the docker extra parameters before. 
much appreciated!

**Comment by ipod86** [comment] 2024-08-17 12:58
@Frooodle 
Where is the log so that I can mount it in docker? 

@timmish 
Can you send me your filter for fail2ban?

**Comment by Frooodle** [comment] 2024-08-17 13:06
All our docker docs show the log folder already you should see it there, /logs

**Comment by timmish** [comment] 2024-08-17 15:55
@ipod86 
Site, it is the most basic thing as I have no clue about regex, but it works 😁

`
[Definition]

failregex = IP: \<ADDR>
`
