### ISSUE TITLE
Change contrast option on existing PDF 

### ISSUE THREAD

**Issue by tweek11** [Frooodle/Stirling-PDF#69] opened 2023-03-15 22:54 UTC
Great project first and foremost!

I had been looking for a replacement for the aging zpex/web-pdf-toolbox (https://hub.docker.com/r/zpex/web-pdf-toolbox) - since it has not been updated since 10/07/2021 - An as of recently I've had to re-pull or restart it to get things working again. 

So Stirling-PDF was perfect timing. 

One of the options that the Zpex project has is the ability to adjust the contrast on existing PDF. Might this be a feature/function that could be added at some point in the future.

Again great project and thank you for your time and consideration.

**Comment by Frooodle** [comment] 2023-03-15 22:56
Duplicate of https://github.com/Frooodle/Stirling-PDF/issues/46 so closing
But yes! it will be a feature added eventually :)

**Comment by Frooodle** [comment] 2023-03-15 22:56
I have worked on this feature a bit before but didnt like how it worked. Ill rework it sometime not this weekend but next

**Closed by Frooodle** 2023-03-15 22:56 UTC

**Comment by tweek11** [comment] 2023-03-15 23:03
Thank you for the update - An of course keep things at your own pace. Nothing of major importance - I'm able to adjust things with the prior project mentioned. I'm sure when the feature is added to Stirling-PDF - I'll be removing the other older docker. 

Again thank you.
