### ISSUE TITLE
[Feature Request] - Adding images (maybe other file types too) directly in Multi Tool

### ISSUE THREAD

**Issue by debugger24** [Frooodle/Stirling-PDF#334] opened 2023-08-31 15:54 UTC
Can we have option to add images and maybe other file types too directly in Multi Tool UI itself, so user will be able to upload mix of pdf, image and other files and it will be converted to pdf on the fly before converting to final single pdf.

**Comment by Frooodle** [comment] 2023-08-31 16:31
Duplicate of https://github.com/Frooodle/Stirling-PDF/issues/278

Do plan to support in future

**Closed by Frooodle** 2023-08-31 16:31 UTC
