### ISSUE TITLE
OCR Doesn't seem to make the PDF searchable

### ISSUE THREAD

**Issue by aj-bayanat** [Frooodle/Stirling-PDF#114] opened 2023-04-27 07:06 UTC
After using OCR on a PDF with a scanned image, the resulting pdf also has just a image, no searchable or text I can copy. 
If I select the option to Produce a text file along with OCR, I can see that the OCR process does run, it just seems the output PDF does not contain this information.

If I use the option to forceOCR on all pages, then even pages that were searchable are now not. 

I am running Stirling-PDF on docker, lastest tag as of 27/04/2023.
App Version 0.6.0
Tesseract Model - tessdata eng (the bigger one, not fast)

**Comment by Frooodle** [comment] 2023-04-27 07:30
Weird are you able to give me the pdf to test against or is it private? I can't reproduce this my side

Maybe it's how the bigger eng data works I will test with that as well tonight or tomorrow

**Comment by aj-bayanat** [comment] 2023-04-27 07:47
Since I am using this at work, that PDF is private, however it happens with all pdf's that I have tried. Will try the fast model and let you know.

**Comment by Frooodle** [comment] 2023-04-27 07:57
I think I found issue 
Mounting that directory is removing some needed files which are already there and which you are missing 
I will change docker file this weekend to ensure those files are kept on mount

**Comment by aj-bayanat** [comment] 2023-04-27 08:09
Yep you nailed it ! Mounted the big eng model file only. (not the directory) and it works !

**Comment by Frooodle** [comment] 2023-04-27 18:52
I have a fix to create a temp folder during build and copy everything from temp to final folder on container startup.
It does mean you wont be able to delete of the old files in that folder but you can add any new ones fine now

**Comment by aj-bayanat** [comment] 2023-04-28 04:07
Sounds like a good fix. Btw when you convert a pdf which you first used ocr to word, the ocr layer disappears and the word document has only an image. Is this intended ? 
Also amazing app! You should post it on r/selfhosted. A pdf manipulator is one  of the most requested apps I’ve seen over the years. The closest is hrconvert but that doesn’t work very well and it’s ui is dated.

**Comment by Frooodle** [comment] 2023-04-28 10:33
It's not ideal but the backend for pdf to word document is libre office so I can't change how it handles the OCR layer sadly

**Comment by Frooodle** [comment] 2023-04-28 10:35
Also i did post on reddit when i first started this app
https://www.reddit.com/r/selfhosted/comments/10pexhn/new_browserbased_pdf_editor_github_link/
I plan to post again when I release V1.0.0

**Comment by Frooodle** [comment] 2023-05-01 21:06
Fixed with extra lang support in latest patch

**Closed by Frooodle** 2023-05-01 21:06 UTC
Labels: bug
