### ISSUE TITLE
No login page

### ISSUE THREAD

**Issue by ontheair81** [Frooodle/Stirling-PDF#526] opened 2023-12-16 09:24 UTC
Running `frooodle/s-pdf:0.16.1-lite` behind nginx reverse proxy on Debian 12.4 via docker. No extraConfigs and no manual changes to settings.yml have been made.

It runs fine, just there is no login page.
Here is my compose file:

```
version: '3.3'

services:
  stirling-pdf:
    container_name: pdf_mydomain_tld
    image: frooodle/s-pdf:0.16.1-lite
    ports:
      - ':8080'
    volumes:
      - /home/user/bind-mounts/stirling-pdf/trainingData:/usr/share/tesseract-ocr/5/tessdata
      - /home/user/bind-mounts/stirling-pdf/extraConfigs:/configs
      - /home/user/bind-mounts/stirling-pdf/customFiles:/customFiles/
    environment:
      - VIRTUAL_HOST=pdf.mydomain.tld
      - LETSENCRYPT_HOST=pdf.mydomain.tld
      - DOCKER_ENABLE_SECURITY=true
      - SECURITY_ENABLE_LOGIN=true
      - SYSTEM_DEFAULT_LOCALE=de-DE
      - SYSTEM_GOOGLE_VISIBILITY=false
    networks:
      - net
    restart: always

networks:
  net:
    external: true
```
What am I doing wrong?
Any help is very appreciated, thank you!

**Comment by Frooodle** [comment] 2023-12-16 09:58
login is currently only supporting in non lite mode i believe, could you try confirm this?

**Comment by Frooodle** [comment] 2023-12-16 09:59
Looking at code lite should support it actually... but it would be good to check if you can

**Comment by Frooodle** [comment] 2023-12-16 10:04
Just confirmed this my side, seems only none like package supports logins, i will try resolve this for next patch

**Comment by ontheair81** [comment] 2023-12-16 10:08
I can confirm, login page works with non lite version. Thank you for pointing this out and your fast response!

**Comment by Frooodle** [comment] 2023-12-16 20:35
released in latest 0.17.0!

**Closed by Frooodle** 2023-12-16 20:35 UTC
Labels: Done for next release

**Comment by misuoka** [comment] 2024-01-20 15:37
stirling-pdf-stirling-pdf-1  |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  106M  100  106M    0     0  2706k      0  0:00:40  0:00:40 --:--:-- 6888k

**Comment by misuoka** [comment] 2024-01-20 15:41
I can download the Stirling-PDF-with-login.jar on the host machine, but it always fails to download the complete JAR file during container build. Where should I place the JAR file I downloaded on the host machine?

**Comment by orrd** [comment] 2025-06-13 01:23
For anyone else who ended on this page while trying to Google things to figure out why login isn't working after following the instructions, it's because in the current version, you now have to install the "fat" version of it to get logins to work.
