### ISSUE TITLE
Feature: watchdir and OCR

### ISSUE THREAD

**Issue by poudenes** [Frooodle/Stirling-PDF#167] opened 2023-05-16 10:52 UTC
Hi All,

What a great tool !!!! Would be nice to see following feature in near future:

1) watch folder to add pdf files that automate get OCR and write pdf back to other folder. Manual select what folder to watch and store new file

2) Watch folder for images to convert them automatic to a PDF file and save this to a different folder.

**Comment by Frooodle** [comment] 2023-05-16 16:57
duplicate of
https://github.com/Frooodle/Stirling-PDF/issues/138

However yes this is planned! but not eta

**Closed by Frooodle** 2023-05-16 16:57 UTC
