### ISSUE TITLE
Merging PDFs fails

### ISSUE THREAD

**Issue by ilorenz0** [Frooodle/Stirling-PDF#233] opened 2023-06-07 21:06 UTC
Hi Frooodle,

first of all, the tool looks amazing, great work! :)

I just installed the docker version and ran into a problem. The merge function just outputs the same files twice, that means when i put the file "file1.pdf" and "file2.pdf" in, it returns "file1_merged.pdf", "file1_merged (1).pdf", "file2_merged.pdf" and "file2_merged (1).pdf".

Maybe you have an idea?
![image](https://github.com/Frooodle/Stirling-PDF/assets/119010403/fde0e951-5498-454a-aed3-fab85383b308)

Best regards,
Lorenz

**Comment by Frooodle** [comment] 2023-06-07 21:09
Ahh I think this was caused by my most recent code release as I reworked the client side download scripts 

For now you can use the multi tool or move to old v9 version 
I'll have a release fix for this by the weekend:)

**Comment by ilorenz0** [comment] 2023-06-08 14:22
Thanks a lot 😊

**Comment by ilorenz0** [comment] 2023-06-08 14:25
I'd like to support you a bit, but i dont have a credit card, do you have paypal maybe?

**Comment by Frooodle** [comment] 2023-06-08 15:03
I do! There should be a PayPal donation button in the front page readme in github

**Comment by Frooodle** [comment] 2023-06-08 21:26
Should be fixed now :)

**Closed** 2023-06-08 21:26 UTC
Labels: bug
