### ISSUE TITLE
[Bug] Selecting PDF files from different directories for merging is overriding the previously selected files

### ISSUE THREAD

**Issue by shiblisec** [Frooodle/Stirling-PDF#529] opened 2023-12-18 04:42 UTC
> The below was reproduced using the docker image

While performing a merge operation on two different pdf files that were located in two different directories I observed the following behaviour.

I selected the first file from directory A, the file gets selected properly.

<img width="939" alt="Screenshot 2023-12-18 at 10 10 07 AM" src="https://github.com/Frooodle/Stirling-PDF/assets/18637512/92657c7e-6aad-4929-a575-efc77833d353">

Then I selected another PDF file from another directory, observe that the previously uploaded file got overriden.

<img width="957" alt="Screenshot 2023-12-18 at 10 10 21 AM" src="https://github.com/Frooodle/Stirling-PDF/assets/18637512/6b938da5-47ac-4cf3-a1cb-bc23c4c43e7d">

**Note:** The files are getting properly selected when I am using the drag and drop functionality

<img width="994" alt="Screenshot 2023-12-18 at 10 09 35 AM" src="https://github.com/Frooodle/Stirling-PDF/assets/18637512/f04765c4-df28-48c0-a821-36063d828059">

**Comment by ManoharMannam** [comment] 2023-12-30 05:40
it is also working fine when i drag and select all files at once, but if i want to select one more file then it is overriding all the existing selected files with the new one.

**Comment by mannam11** [comment] 2023-12-30 08:34
@DimK10 @Frooodle I have provide a fix for this issue can you check on this

**Comment by DimK10** [comment] 2023-12-30 09:20
@mannam11 Great job, but the files to merge also need to be merged in the final merged pdf. In your branch, i tested this functionality, and it was not working. I selected two different pdfs by using the input, and they appeared properly in the section for the selected files, but when i tried to merge them, only the last one was used. Do you want me to assign this one to you? I am currently working on it, but if you want to make the fix, i could be more useful in another issue.

**Comment by mannam11** [comment] 2023-12-30 09:56
i thought the issue is only with overring the previously selected files.
sure, you can assign this to me. i will work on it

**Comment by DimK10** [comment] 2023-12-30 10:03
@mannam11 when I thought it would be nice to be able to add additional files, and maybe add an additional button to remove a file. Either way, the issue is all yours! Feel free to contact me if you want any help or tips

**Comment by mannam11** [comment] 2023-12-30 10:04
@DimK10 I think we can close this issue as this is solve. 
for merging error i have already created a new issue so that i can work on that issue.

**Comment by mannam11** [comment] 2023-12-30 10:07
@DimK10 so you are expecting a button or something to remove already selected files ,anyway we have the option to add the multiple files.
is my understanding correct here..?

**Comment by DimK10** [comment] 2023-12-30 10:17
@mannam11 My thought process is this: (if you like to do it differently, or you think that something is not right, feel free to say so). The user selects, lets say two files. The user then decides to select another two. The two old ones are retained in an array, and the new ones are added too. In the files selected section, with the arrow buttons there is an additional remove button for each file, which removes that file from the array. When the user presses the merge button, that array of files is sent to the backend and those files are merged. For a global array of files (which you might need because there are two or three js scripts involved in the whole process) I used the window object (window.files) which can be referenced in any js script.

**Comment by mannam11** [comment] 2023-12-30 10:24
@DimK10 I also think in the same way. so the final choice is with users whether they want to merge the all selected files or remove some. 
I will work on to add a remove button for every file that has been selected to merge.

**Comment by DimK10** [comment] 2023-12-30 10:25
Great! Keep going! I'm excited to see the final result!

**Comment by mannam11** [comment] 2023-12-30 11:18
@DimK10 added the remove button and created a PR

**Comment by DimK10** [comment] 2023-12-30 11:20
Great! Please add for request review the @Frooodle

**Comment by mannam11** [comment] 2023-12-30 11:23
@Frooodle I have solved overriding the previous files issue and added a new remove button for removing the selected files.
can you please review my PR's.

**Comment by mannam11** [comment] 2023-12-30 12:14
@DimK10  @Frooodle I think we can close this issue now.

**Closed** 2023-12-30 12:22 UTC
Labels: bug, Front End

**Comment by shiblisec** [comment] 2024-01-05 05:25
Thanks for the fix, but I am still able to reproduce the issue, in the newer version `0.18.1` the previous file are getting overridden as soon as I am selecting another file from different directory.

**Comment by Frooodle** [comment] 2024-01-05 10:17
Will be released next patch
