### ISSUE TITLE
Support for Reverse proxies

### ISSUE THREAD

**Issue by maxbrueckl** [Frooodle/Stirling-PDF#14] opened 2023-01-31 09:11 UTC
I would really appreciate if you could add support for reverse proxies like Apache, Caddy, Traefik and others.

To support reverse proxies in spring boot according to the [docs](https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.webserver.use-behind-a-proxy-server) what you have to do is simple.
Add this line to the [application.properties](https://github.com/Frooodle/Stirling-PDF/blob/main/src/main/resources/application.properties):
`server.forward-headers-strategy=NATIVE`

**Comment by Frooodle** [comment] 2023-01-31 11:21
Odd i am running mine behind a nginx and it works fine, I will add this so headers can forward as well though but that shouldnt effect things...

Thanks for providing doc

**Comment by tom472** [comment] 2023-01-31 14:05
Awesome tool - really think it will be useful.
I just tried this with nginx as a reverse proxy and the home page works but clicking on any of the links does not take me to the sub-page(s).
This was just with a very simple `proxy-pass` line in the `nginx.conf` file.  

Could you post the config you are using in your `nginx.conf` file for proxying s-pdf?

**Comment by Frooodle** [comment] 2023-01-31 14:06
I use Nginx Proxy Manager which generates the config automatically
But if people are having issues ill try add the suggested flag and we can see if it works

**Comment by tom472** [comment] 2023-01-31 14:12
The config being created/used should still be visible or readable somewhere in Nginx Proxy Manager or on your file system.  
Thanks for looking into this ..

**Comment by Frooodle** [comment] 2023-01-31 14:12
I have just pushed a version 0.2.2 with config from @maxbrueckl  suggestion https://github.com/Frooodle/Stirling-PDF/pull/16/files.
If you want to manually update to that (rather than latest tag)
And let me know if it works

**Comment by tom472** [comment] 2023-01-31 14:47
Still didn't work yet .. 

Details:  
`image   | frooodle/s-pdf:0.2.2`  

I am using port `8888` on the server and forwarding to `8080` in the container via the line below in the docker-compose.yml.
```
    ports:
        - '${IP_ADDRESS}:8888:8080'
```  


Very simple/basic NGINX proxy-pass config:  
```
    location /pdf/ {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Connection "";
        proxy_pass http://host.server:8888/;
    }
```

Again main page loads - none of the links / sub-pages load.

**Comment by Frooodle** [comment] 2023-01-31 15:34
Are there any errors in docker log when you access it?
Using location as anything other than / I cant even get to home page

**Comment by tom472** [comment] 2023-01-31 15:43
No errors logged to the `s-pdf` app log.  

The NGINX logs get this when the URL is accessed:
`"GET /pdf/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 ..... `
`"GET /home HTTP/1.1" 200 73210 "-" "Mozilla/5.0 .....`

**Comment by tom472** [comment] 2023-01-31 15:52
So Just FYI - Yes I can confirm that using a root level location does work correctly.  

e.g.  
Using this NGINX config and a root location works as expected:
```
     location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
        proxy_pass http://host.server:8888/;
   }
```

Would be great to get this working via a `/location` configuration as well if possible.

Thanks again for the tool and for looking into this.

**Comment by Frooodle** [comment] 2023-01-31 16:53
Can you try now with 0.2.2 again (repull version as its different image now)

**Comment by tom472** [comment] 2023-01-31 17:07
OK deleted the current 0.2.2 image.  
Pulled the new image and ... 
Yes - this does appear to be working now - at least as far as loading the additional pages correctly.
I'll test actual functionality soon - but the initial issue is resolved.  

And to proxy this with NGINX, currently all I have in the `nginx.conf` file for this is:
```
    location /pdf/ {
        proxy_pass http://host.server:8888/;
    }
```

**Comment by Frooodle** [comment] 2023-01-31 17:16
awesome let me push this to latest tag now

**Comment by Frooodle** [comment] 2023-01-31 17:41
Closing issue, let me know if it is still ongoing in 'latest' tag

**Closed by Frooodle** 2023-01-31 17:41 UTC

**Comment by maxbrueckl** [comment] 2023-01-31 18:21
Thanks for integrating the change ❤️ 

Works like a charm for me now.
About my setup: traefik v2 (current: 2.9.6) secured with authelia.

**Comment by porjo** [comment] 2024-01-04 10:14
I just ran into this problem. I'm also running Stirling PDF behind behind a reverse proxy (caddy) using path `/pdf` . I noticed that, for example, crop operation is sending a request to `/api/v1/general/crop` (which results in 404 error) rather than `/pdf/api/v1/general/crop`. I tried setting `SYSTEM_ROOTURIPATH=/pdf` but it makes no difference.

**Comment by EmilGH** [comment] 2024-05-22 13:10
I posted a working Apache Reverse Proxy config here: [https://github.com/Stirling-Tools/Stirling-PDF/discussions/1273](https://github.com/Stirling-Tools/Stirling-PDF/discussions/1273)

**Comment by 16mc1r** [comment] 2024-08-06 10:28
> Thanks for integrating the change ❤️
> 
> Works like a charm for me now. About my setup: traefik v2 (current: 2.9.6) secured with authelia in docker.

@maxbrueckl  could you be so kind as to share your traefik ingress/ingressoute/middleware manifests? Im trying the same but it doesnt work.

### Background
Im currently trying to put stirlingpdf (v.26.1, image id `docker.io/frooodle/s-pdf@sha256:a5a8c2df471a760596dc3b2701a60af755a6fd63c85c73fa52c199b08504d584`) behind a traefik reverse proxy in microk8s.

It works with normal ingress in standard configuration (loadbalancer-ip/) or with `SYSTEM_ROOTURIPATH` and the ingress path set to `/pdf`. Then I can reach it via `loadbalancer-ip/pdf` as intended.

But, when i use the traefik `IngressRoute` and `Stripprefix` middleware so i can reach it with the `pdf` prefix its not communicated to stirlingpdf. As far as I understand [traefik-middleware](https://doc.traefik.io/traefik/middlewares/http/stripprefix/) the prefix should be stripped and added to the request header as `X-Forwarded-Prefix` so that springboot picks it up and works with the reverse proxy.

**Comment by SckyzO** [comment] 2024-11-12 02:01
> Thanks for integrating the change ❤️
> 
> Works like a charm for me now. About my setup: traefik v2 (current: 2.9.6) secured with authelia in docker.

Hello, 

Is it possible de share your docker compose ? 
I try to run with traefik too, but i can't. 

Regards,
